### ISSUE TITLE
Problem with dual monitor setup and dynamic tagging

### ISSUE THREAD

**Issue by zioalex** [pw4ever/awesome-wm-config#4]
Hi,
I just started to use your awesome config. It is very nice. 

I have some problem with the dynamic tagging and my dual setup monitor.

Usually when I finish to work i suspend my laptop and reset the display only to the laptop display later on when I switch back to the dual monitor setup all the tags in the different monitors are screwed! Plus I have on both monitor the default awesome tag (1..9) .

I do not see where the tags are written. I thought in ~/.cache/awesome but I cannot find every tag I have.

Do you have any advice?

**Comment by pw4ever** [comment]
Thanks for trying this out. I have a few clarification questions.

First, what is your setup (OS, version, etc.). "ModKey + \" may help.

>  suspend my laptop and reset the display only to the laptop display

What do you mean by "reset the display only to the laptop display" when your laptop is suspended?

> when I switch back to the dual monitor setup all the tags in the different monitors are screwed

When you switch from dual monitor setup to single display, the tags on secondary screenshould be appended to the last existing screen (in this case, the primary display). This is by design. Otherwise, you would not have access to applications/clients on those tags while the secondary display is off. Persistent tagging does not mean it remembers tags on displays that are explicitly _turned_ off by, .e.g, "xrandr".

Also, could you be more specific about what you mean by "screwed"? Error messages? Get only the default tag "genesis"?

>  have on both monitor the default awesome tag (1..9)

Do you create the tags yourself or do you modify the configs to have the default tags? By default, you get a single "genesis" tag on the primary screen.

> I thought in ~/.cache/awesome but I cannot find every tag I have

Yes, by default you should find persistent tagging info written under "~/.cache/awesome". What do you see under that folder?

Wei.

**Comment by pw4ever** [comment]
As a reference, I have an old Thinkpad X61s laptop running this config with dual-monitor setup (laptop display plus a VGA external display). I suspend and resume all the time; the persistent tagging works as expected.

**Comment by zioalex** [comment]
Hi Wei,
thanks for your nice setup. I will try to clarify.,
My setup:
awesome v3.5.6 on Gentoo (updated) on an HP EliteBook 9740m 

With "reset the display only to the laptop display"  I mean:
I use usually my laptop with a dual external monitor setup with a docking station without using the laptop display.

When I suspend the laptop I change the display config automatically ( through xrand ) to the laptop display otherwise X became crazy and I cannot take anymore control of the laptop.

I got the fact that the tags are appended to the lat screen and that is good . What I've seen is that across awesome restart more standard tag [ 1-9 ] has been added to the current tags list creating a mess.

What I have seen this morning is that one of the new display had all the tags as yesterday while the other didn't have anyone, I had to create it manually otherwise I could not ran anything.

I added some tags myself ( mail , browser, etc )

Would be great to have the possibility to move the tags across different screen ...

This is the content of .cache/awesome:

> ls -aR
> .:
> .  ..  awesome-autostart-once-18  awesome-client-tags-18  history  history_eval  lastwallpaper  serialized.lua
> ./awesome-client-tags-18:
> .  ..

I expected to see some reference to the tags there.

**Comment by pw4ever** [comment]
@zioalex Thanks for the clarification.

> awesome v3.5.6 on Gentoo (updated) on an HP EliteBook 9740m

Mine is v3.5.6 on Arch Linux; our setups are similar enough and should not have much behavior differences.

I have never tested the setup on a docking station. But I have a dual-GPU laptop (Thinkpad W530) that had similar issues resuming with the standalone GPU on (I have to xrandr off the secondary display prior to suspending); I got annoyed enough, so I do not use it for multi-monitor setup, and decide in the future I will not buy a laptop with two GPUs.

> What I've seen is that across awesome restart more standard tag [ 1-9 ] has been added to the current tags list creating a mess.

If you have not modified the Awesome config, this indicates Awesome runs into some issue during the resume. I only see the default [1-9] tags pop up when I make some errors in the config and restart Awesome during development. I have no idea what went wrong here for you; maybe you want to look into suspend/resume hooks on your laptop concerning docking/undocking, for example.

> What I have seen this morning is that one of the new display had all the tags as yesterday while the other didn't have anyone, I had to create it manually otherwise I could not ran anything.

This is expected behavior. I agree with you it would be "great to have the possibility to move the tags across different screen". I may add and bind this behavior to, e.g., <kbd>Modkey</kbd><kbd>Ctrl</kbd><kbd>o</kbd>, in the future; if you could hack this up and send a patch in, that would be even better :)

> I expected to see some reference to the tags there.

Your expectation is correct. If this is what you see after a resume from suspend, then the Awesome states are not correctly persisted. I would suggest you trying manually restarting Awesome once (<kbd>Modkey</kbd><kbd>Ctrl</kbd><kbd>r</kbd> and "yes") and see what is there under `$HOME/.cache/awesome`, just for sanity checking.

For reference, below is what I got on the two-monitor setup I mentioned in the previous post.

``` shell
$ ls ~/.cache/awesome 
awesome-autostart-once-c2  awesome-restart-tags-c2.1
awesome-autostart-once-c4  awesome-restart-tags-c2.2
awesome-client-tags-c2     awesome-restart-tags-c2-selected.1
awesome-restart-tags-c2    awesome-restart-tags-c2-selected.2
awesome-restart-tags-c2.0  history
$ cat awesome-restart-tags-c2.*
2
genesis
1t
$ ls awesome-restart-tags-c2
0.0-10485761.0  0.0-6291457.0
```

**Comment by pw4ever** [comment]
@zioalex 
I have added "moving tag to prev/next screen" that are bound to <kbd>Modkey</kbd><kbd>Ctrl</kbd><kbd>o</kbd>/<kbd>Modkey</kbd><kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>o</kbd> respectively. This should alleviate the pain to recreate tags on new screen.

**Comment by zioalex** [comment]
Hi Wei,
thanks for adding that functionality. I will add it immediately! :-) 
I thought to look in the code but you have been really quicker than me!

Regarding my suspend/hook I use xrandr to set the display to only the laptop screen everytime I go in suspend/hibernate mode to avoid any problem with X. But this is the only thing I do.

Regarding the tagging something is not working properly.

My cache dir is updated but it is empty also after a restart:

```
> ls -al
total 8
drwxr-xr-x 2 asurace asurace 4096 Feb 14 16:34 .
drwxr-xr-x 3 asurace asurace 4096 Feb 14 16:34 ..
```

**Comment by pw4ever** [comment]
@zioalex 

> thanks for adding that functionality. I will add it immediately! 

Glad it would be useful. That is the purpose of releasing this config on GitHub :)

One way I would recommend using this config (which is what I am using with the `local-1pengw` Git branch) is to make your customizations in a local Git branch (e.g., `local-zioalex`) that is basing off `master`. You can later do `git fetch origin; git merge master` in `local-zioalex` to merge new upstream changes.

> Regarding my suspend/hook I use xrandr to set the display to only the laptop screen everytime I go in suspend/hibernate mode to avoid any problem with X

I suspect putting xrandr in suspend hook would mess up this Awesome config's idea of tags since the whole process (xrandr reset + machine goes into S3 sleep state) happens so quickly that dynamic tagging files have not been serialized before the machine goes into S3.

One way to test this is to manually do the xrandr setting without suspending, and see if the dynamic tagging restoration works propoerly and the tags files are serialized in `$HOME/.config/awesome`). If the serialization happens correctly, maybe you can introduce an artificial `sleep 5` (adjust the time to how soon the dynamic tagging is stablized) in the suspend hook

To make sure we are looking at the right cache folder, use `awesome-client` to do the following:

``` lua
naughty=require("naughty")
awful_util=require("awful.util")
naughty.notify({text=awful_util.getdir("cache")})
```

... and look at the notification message on the top right corner for the path.

**Comment by zioalex** [comment]
The git usage proposed is a great idea! Thanks.
Regarding the tags seems that now they are working properly.
The cache dir as per the command above:
`awesome#naughty=require("naughty")
awesome#awful_util=require("awful.util")
awesome#naughty.notify({text=awful_util.getdir("cache")})
`
is exactly ~/.cache/awesome

But it is not always populated also after a manual awesome restart!.

**Comment by pw4ever** [comment]
@zioalex 
It appears that, with Awesome v3.5.8 and 1.7.18 config, I do not see "cache" folder populated on my computer, but the dynamic tagging appear to work fine.

I propose we enjoy the bless of ignorance on this matter, and wish the persistent tagging will continue to work as it should :)

**Comment by zioalex** [comment]
AhhAhhh. I would say that in this case our ignorance is enough wise! :-D
